version: 2.1

executors:
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: vss
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: ['--character-set-server=utf8mb4']

jobs:
  build:
    executor: openjdk11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - v1-dependencies-
      - run:
          name: Run spotlessCheck
          command: ./gradlew spotlessCheck
      - run:
          name: Run test
          command: ./gradlew test
      - store_artifacts:
          path: build/reports
      - store_test_results:
          path: build/test-results
          destination: test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}

workflows:
  version: 2
  build:
    jobs:
      - build
