ALTER TABLE tasks DROP COLUMN memo1;
ALTER TABLE tasks DROP COLUMN memo2;
ALTER TABLE tasks DROP COLUMN memo3;
ALTER TABLE tasks DROP COLUMN memo4;
ALTER TABLE tasks DROP COLUMN memo5;
ALTER TABLE tasks DROP COLUMN memo6;
