ALTER TABLE tasks ADD COLUMN memo1 VARCHAR(10);
ALTER TABLE tasks ADD COLUMN memo2 VARCHAR(10);
ALTER TABLE tasks ADD COLUMN memo3 VARCHAR(10);
ALTER TABLE tasks ADD COLUMN memo4 VARCHAR(10);
ALTER TABLE tasks ADD COLUMN memo5 VARCHAR(10);
ALTER TABLE tasks ADD COLUMN memo6 VARCHAR(10);
